# Generated by Django 6.0.2 on 2026-02-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_estoque_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
